version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing SonarQube Scanner...
      - curl -o sonar-scanner-cli.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
      - unzip sonar-scanner-cli.zip -d /opt
      - export PATH=$PATH:/opt/sonar-scanner-4.6.2.2472-linux/bin
  build:
    commands:
      - chmod +x run.sh
      - ./run.sh
